options:
  merge-default-rules: false
rules:
  bem-depth:
    - 0
    - max-depth: 1
  border-zero:
    - 0
    - convention: zero
  brace-style:
    - 0
    - allow-single-line: true
  class-name-format:
    - 0
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 0
    - ignore-single-line-rulesets: true
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline:
    - 0
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 0
    - convention: hyphenatedlowercase
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 0
  nesting-depth:
    - 1
    - max-depth: 4
  no-color-literals: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties:
    - 1
    - extra-properties:
        - "-webkit-overflow-scrolling"
        - scrollbar-width
        - overscroll-behavior
        - gap
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 1
  placeholder-in-extend: 0
  placeholder-name-format:
    - 0
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - ignore-custom-properties: true
      order:
        # Content
        - counter-reset
        - counter-increment

        - content
        - quotes

        - list-style
        - list-style-position
        - list-style-type
        - list-style-image

        - table-layout
        - empty-cells
        - caption-side

        # Box
        - "-webkit-appearance"
        - appearance
        - display
        - visibility
        - float
        - clear

        - grid
        - grid-after
        - grid-area
        - grid-auto-columns
        - grid-auto-flow
        - grid-auto-rows
        - grid-before
        - grid-column
        - grid-column-end
        - grid-column-gap
        - grid-column-start
        - grid-columns
        - grid-end
        - grid-gap
        - grid-row
        - grid-row-end
        - grid-row-gap
        - grid-row-start
        - grid-rows
        - grid-start
        - grid-template
        - grid-template-areas
        - grid-template-columns
        - grid-template-rows

        - flex
        - flex-align
        - flex-basis
        - flex-direction
        - flex-wrap
        - flex-flow
        - flex-grow
        - flex-shrink
        - flex-order
        - flex-pack

        - break-inside
        - break-before
        - break-after
        
        - align-items
        - align-self
        - justify-content
        - order

        - position
        - top
        - bottom
        - left
        - right
        - z-index

        - margin
        - margin-top
        - margin-bottom
        - margin-left
        - margin-right

        - "-webkit-box-sizing"
        - "-moz-box-sizing"
        - box-sizing
        - width
        - max-width
        - min-width
        - height
        - max-height
        - min-height

        - overflow
        - overflow-x
        - overflow-y
        - "-ms-overflow-x"
        - "-ms-overflow-y"
        - "-ms-overflow-style"

        - "-webkit-overflow-scrolling"
        - overscroll-behavior
        - scroll-behavior
        - scroll-snap-type
        - scroll-snap-type-x
        - scroll-snap-type-y
        - scroll-snap-align
        - scroll-snap-stop
        - scroll-margin
        - scroll-margin-block
        - scroll-margin-block-start
        - scroll-margin-block-end
        - scroll-margin-inline
        - scroll-margin-inline-start
        - scroll-margin-inline-end
        - scroll-margin-top
        - scroll-margin-bottom
        - scroll-margin-left
        - scroll-margin-right
        - scroll-padding
        - scroll-padding-block
        - scroll-padding-block-start
        - scroll-padding-block-end
        - scroll-padding-inline
        - scroll-padding-inline-start
        - scroll-padding-inline-end
        - scroll-padding-top
        - scroll-padding-bottom
        - scroll-padding-left
        - scroll-padding-right

        - clip
        - clip-path

        - border
        - border-width
        - border-style
        - border-color
        - border-top
        - border-top-width
        - border-top-style
        - border-top-color
        - border-bottom
        - border-bottom-width
        - border-bottom-style
        - border-bottom-color
        - border-right
        - border-right-width
        - border-right-style
        - border-right-color
        - border-left
        - border-left-width
        - border-left-style
        - border-left-color
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius

        - "-webkit-border-image"
        - "-moz-border-image"
        - "-o-border-image"
        - border-image
        - "-webkit-border-image-source"
        - "-moz-border-image-source"
        - "-o-border-image-source"
        - border-image-source
        - "-webkit-border-image-slice"
        - "-moz-border-image-slice"
        - "-o-border-image-slice"
        - border-image-slice
        - "-webkit-border-image-width"
        - "-moz-border-image-width"
        - "-o-border-image-width"
        - border-image-width
        - "-webkit-border-image-outset"
        - "-moz-border-image-outset"
        - "-o-border-image-outset"
        - border-image-outset
        - "-webkit-border-image-repeat"
        - "-moz-border-image-repeat"
        - "-o-border-image-repeat"
        - border-image-repeat
        - border-spacing
        - border-collapse

        - background
        - background-color
        - background-image
        - '-ms-filter:\\''progid:DXImageTransform.Microsoft.gradient'
        - "filter:progid:DXImageTransform.Microsoft.gradient"
        - "filter:progid:DXImageTransform.Microsoft.AlphaImageLoader"
        - background-repeat
        - background-attachment
        - background-position
        - background-position-x
        - background-position-y
        - "-webkit-background-clip"
        - "-moz-background-clip"
        - background-clip
        - background-origin
        - "-webkit-background-size"
        - "-moz-background-size"
        - "-o-background-size"
        - background-size

        - padding
        - padding-top
        - padding-bottom
        - padding-left
        - padding-right

        - "-webkit-box-shadow"
        - "-moz-box-shadow"
        - box-shadow
        - opacity
        - "filter:progid:DXImageTransform.Microsoft.Alpha(Opacity"
        - '-ms-filter:\\''progid:DXImageTransform.Microsoft.Alpha'
        - "filter:alpha(opacity"
        - "-ms-interpolation-mode"

        - outline
        - outline-offset
        - outline-width
        - outline-style
        - outline-color

        # Text
        - color

        - font
        - font-family
        - font-size
        - font-style
        - font-weight
        - font-variant
        - font-variant-numeric
        - font-feature-settings
        - font-size-adjust
        - font-stretch
        - font-effect
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - font-smooth
        - line-height

        - "-webkit-hyphens"
        - "-moz-hyphens"
        - hyphens
        - text-align
        - "-webkit-text-align-last"
        - "-moz-text-align-last"
        - "-ms-text-align-last"
        - text-align-last
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-style
        - text-emphasis-position
        - text-decoration
        - text-decoration-style
        - text-decoration-line
        - text-decoration-color
        - text-indent
        - text-justify
        - text-outline
        - "-ms-text-overflow"
        - text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - text-shadow
        - text-transform
        - text-wrap

        - vertical-align
        - white-space
        - "-webkit-text-size-adjust"
        - "-ms-text-size-adjust"
        - "-ms-word-wrap"
        - word-wrap
        - overflow-wrap
        - "-ms-word-break"
        - word-break
        - word-spacing
        - letter-spacing
        - "-moz-tab-size"
        - "-o-tab-size"
        - tab-size

        - "-webkit-user-select"
        - "-moz-user-select"
        - "-ms-user-select"
        - "-o-user-select"
        - user-select

        # Animation
        - stroke
        - fill
        - filter

        - "-webkit-transform"
        - "-moz-transform"
        - "-ms-transform"
        - "-o-transform"
        - transform
        - "-webkit-transform-origin"
        - "-moz-transform-origin"
        - "-ms-transform-origin"
        - "-o-transform-origin"
        - transform-origin

        - "-webkit-transition"
        - "-moz-transition"
        - "-ms-transition"
        - "-o-transition"
        - transition
        - "-webkit-transition-delay"
        - "-moz-transition-delay"
        - "-ms-transition-delay"
        - "-o-transition-delay"
        - transition-delay
        - "-webkit-transition-timing-function"
        - "-moz-transition-timing-function"
        - "-ms-transition-timing-function"
        - "-o-transition-timing-function"
        - transition-timing-function
        - "-webkit-transition-duration"
        - "-moz-transition-duration"
        - "-ms-transition-duration"
        - "-o-transition-duration"
        - transition-duration
        - "-webkit-transition-property"
        - "-moz-transition-property"
        - "-ms-transition-property"
        - "-o-transition-property"
        - transition-property
        - "-webkit-animation"
        - "-moz-animation"
        - "-ms-animation"
        - "-o-animation"

        - animation
        - "-webkit-animation-name"
        - "-moz-animation-name"
        - "-ms-animation-name"
        - "-o-animation-name"
        - animation-name
        - "-webkit-animation-duration"
        - "-moz-animation-duration"
        - "-ms-animation-duration"
        - "-o-animation-duration"
        - animation-duration
        - "-webkit-animation-play-state"
        - "-moz-animation-play-state"
        - "-ms-animation-play-state"
        - "-o-animation-play-state"
        - animation-play-state
        - "-webkit-animation-timing-function"
        - "-moz-animation-timing-function"
        - "-ms-animation-timing-function"
        - "-o-animation-timing-function"
        - animation-timing-function
        - "-webkit-animation-delay"
        - "-moz-animation-delay"
        - "-ms-animation-delay"
        - "-o-animation-delay"
        - animation-delay
        - "-webkit-animation-iteration-count"
        - "-moz-animation-iteration-count"
        - "-ms-animation-iteration-count"
        - "-o-animation-iteration-count"
        - animation-iteration-count
        - "-webkit-animation-direction"
        - "-moz-animation-direction"
        - "-ms-animation-direction"
        - "-o-animation-direction"
        
        - pointer-events
        - "-ms-touch-action"
        - touch-action
        - cursor
        - resize
        - src
        - zoom
        
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - "%"
      per-property: {}
  quotes:
    - 1
    - style: double
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3
        - 4
  single-line-per-selector: 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon: 1
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1